### ISSUE TITLE
Inaccuracy obtained results 

### ISSUE THREAD

**Issue by 1Husin-Alhaj** [vporpo/zofi#3]
I've performed a lot of FI experiments on Mibench programs and can say that ZOFI is generating illogical and totally unrealistic results. 
A fault injection campaign has high run-to-run variation when we inject using same "inject-exec-to" arg. 
How fault injection results into control register has the same results when we inject faults into general data registers?!!!!!

**Comment by vporpo** [comment]
I fixed a bug related to the bit selection, perhaps this will fix the issue that you are observing.
I also added a two new options: `-force-inject-to-reg` and `-force-inject-to-bit`, which you may find useful.
